/*
 * Created Date       : 11-04-2026
 * Description        : Definisi Antarmuka Data (IDL) untuk Streaming Radar.
 *                      Kontrak data standar untuk sinkronisasi OpenDDS C++ dan React UI.
 *
 * Changelog:
 *   - 0.1.0 (11-04-2026): Struktur awal matching RadarTrack Typescript interface.
 */

module RadarSystem {

    enum ClassificationType {
        UNKNOWN,
        FRIEND,
        HOSTILE,
        NEUTRAL,
        CENTER
    };

    @topic
    struct RadarTrack {
        @key string trackId;
        double lat;
        double lon;
        float speed;
        float heading;
        float altitude;
        long long timestamp;
        ClassificationType classification;
    };
};
