version: "3.9"

services:
  web:
    build: .
    image: ${SERVICE_NAME:-stream-radar-frontend}:latest
    container_name: ${SERVICE_NAME:-radar-webdds}
    env_file:
      - .env
    ports:
      - "${TARGET_PORT:-3000}:${SERVICE_PORT:-3000}"
    volumes:
      # Sinkronisasi folder lokal ini ke dalam container
      # Bertujuan agar "Live Reload / Hot Refresh" bekerja!
      - .:/app
      - /app/node_modules
    restart: unless-stopped
